<?php

namespace Database\Seeders;

use App\Models\Patient;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PatientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $patients = [
            [
                'id' => 1,
                'nama_lengkap' => 'Sepawarni',
                'jenis_kelamin' => 'P',
                'umur' => 44,
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'created_at' => Carbon::create(2024, 11, 3),
                'no_hp' => '081288336186',
                'nik' => null,
                'alamat' => 'Griya Cilengsi 5 A7 No 7'
            ],
            [
                'id' => 2,
                'nama_lengkap' => 'Eti Kusniati',
                'jenis_kelamin' => 'P',
                'umur' => null,
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'created_at' => Carbon::create(2024, 11, 5),
                'no_hp' => '081219489193',
                'nik' => null,
                'alamat' => ''
            ],
            [
                'id' => 3,
                'nama_lengkap' => 'Aimar Hamizan',
                'jenis_kelamin' => 'L',
                'umur' => 9,
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'created_at' => Carbon::create(2024, 11, 5),
                'no_hp' => null,
                'nik' => null,
                'alamat' => 'Griya Cileungsi 5'
            ],
            [
                'id' => 4,
                'nama_lengkap' => 'Qonita Shaviyya Az Zahra',
                'jenis_kelamin' => 'P',
                'umur' => 10,
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'created_at' => Carbon::create(2024, 11, 11),
                'no_hp' => null,
                'nik' => null,
                'alamat' => 'Griya Cileungsi 5'
            ],
            [
                'id' => 5,
                'nama_lengkap' => 'Riesca Setya Permata',
                'jenis_kelamin' => 'P',
                'umur' => 31,
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'created_at' => Carbon::create(2024, 11, 12),
                'no_hp' => '08568221618',
                'nik' => null,
                'alamat' => 'Griya Cileungsi 5'
            ],
            [
                'id' => 6,
                'nama_lengkap' => 'Gathan Azka Diputra',
                'jenis_kelamin' => 'L',
                'umur' => 6,
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'created_at' => Carbon::create(2024, 11, 16),
                'no_hp' => null,
                'nik' => null,
                'alamat' => 'Perum Merkasari Permai Blok B II A5 RT 01 RW 08'
            ],
            [
                'id' => 7,
                'nama_lengkap' => 'Sarwono',
                'jenis_kelamin' => 'P',
                'umur' => 34,
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'created_at' => Carbon::create(2024, 11, 16),
                'no_hp' => '085885551808',
                'nik' => null,
                'alamat' => 'Griya Cileungsi 5'
            ],
            [
                'id' => 8,
                'nama_lengkap' => 'Wahyu Purnama Putra',
                'jenis_kelamin' => 'L',
                'umur' => 34,
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'created_at' => Carbon::create(2024, 11, 21),
                'no_hp' => '085697639047',
                'nik' => '3201072103900005',
                'alamat' => 'Perum Merkasari Permai Blok B II A5 RT 01 RW 08'
            ],
            [
                'id' => 9,
                'nama_lengkap' => 'Rahayu Widyaningsih',
                'jenis_kelamin' => 'P',
                'umur' => 35,
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'created_at' => Carbon::create(2024, 11, 25),
                'no_hp' => '081280851106',
                'nik' => null,
                'alamat' => 'Griya Cileungsi 5'
            ],
            [
                'id' => 10,
                'nama_lengkap' => 'Jaya Imam',
                'jenis_kelamin' => 'L',
                'umur' => null,
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'created_at' => Carbon::create(2024, 11, 27),
                'no_hp' => '081291972453',
                'nik' => null,
                'alamat' => 'Griya Cileungsi 5'
            ],
            [
                'id' => 11,
                'nama_lengkap' => 'Emi Widastuti',
                'jenis_kelamin' => 'P',
                'umur' => null,
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'created_at' => Carbon::create(2024, 11, 27),
                'no_hp' => '082310444545',
                'nik' => null,
                'alamat' => 'Griya Cileungsi 5'
            ],
            [
                'id' => 12,
                'nama_lengkap' => 'Hamdandih',
                'jenis_kelamin' => 'L',
                'umur' => 23,
                'tempat_lahir' => 'Temanggung',
                'tanggal_lahir' => Carbon::create(2001, 12, 19),
                'created_at' => Carbon::create(2024, 11, 30),
                'no_hp' => '082179427463',
                'nik' => null,
                'alamat' => 'Gg halim puri harmoni 5 blok A no 4'
            ],
            [
                'id' => 13,
                'nama_lengkap' => 'Hanum Clarissa Wardani',
                'jenis_kelamin' => 'P',
                'umur' => 5,
                'tempat_lahir' => null,
                'tanggal_lahir' => Carbon::create(2019, 9, 9),
                'created_at' => Carbon::create(2024, 12, 2),
                'no_hp' => '081543376942',
                'nik' => null,
                'alamat' => 'Griya Cileungsi 5 Blok E 10 no 8'
            ],
            [
                'id' => 14,
                'nama_lengkap' => 'Mauriceka Mellani',
                'jenis_kelamin' => 'P',
                'umur' => 22,
                'tempat_lahir' => 'Wonogiri',
                'tanggal_lahir' => Carbon::create(2002, 6, 21),
                'created_at' => Carbon::create(2024, 12, 2),
                'no_hp' => '085173009676',
                'nik' => null,
                'alamat' => 'Griya Cileungsi 5 Blok E 10 no 6'
            ],
            [
                'id' => 15,
                'nama_lengkap' => 'Diska Pramesti',
                'jenis_kelamin' => 'P',
                'umur' => 22,
                'tempat_lahir' => 'Ciamis',
                'tanggal_lahir' => Carbon::create(2002, 9, 4),
                'created_at' => Carbon::create(2024, 12, 5),
                'no_hp' => '081936182375',
                'nik' => '3201074409020002',
                'alamat' => 'Griya Cileungsi 5 Blok E3 no 10'
            ],
            [
                'id' => 16,
                'nama_lengkap' => 'Alip',
                'jenis_kelamin' => 'L',
                'umur' => 22,
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'created_at' => Carbon::create(2024, 12, 10),
                'no_hp' => '085714941039',
                'nik' => null,
                'alamat' => 'Griya Cileungsi 5'
            ],
            [
                'id' => 17,
                'nama_lengkap' => 'Ragil Sri Kusumawati',
                'jenis_kelamin' => 'P',
                'umur' => 40,
                'tempat_lahir' => 'Klaten',
                'tanggal_lahir' => Carbon::create(1984, 3, 23),
                'created_at' => Carbon::create(2024, 12, 23),
                'no_hp' => '089506123507',
                'nik' => null,
                'alamat' => ''
            ],
            [
                'id' => 18,
                'nama_lengkap' => 'Muhammad Rizqy Sudiro',
                'jenis_kelamin' => 'L',
                'umur' => 14,
                'tempat_lahir' => 'Bekasi',
                'tanggal_lahir' => Carbon::create(2010, 11, 8),
                'created_at' => Carbon::create(2024, 12, 26),
                'no_hp' => '083896916900',
                'nik' => null,
                'alamat' => 'Perum D\'Sieranz Town Square Blok A5, Desa Gandoang'
            ],
            [
                'id' => 19,
                'nama_lengkap' => 'Maulida Aqilah Shalihah',
                'jenis_kelamin' => 'P',
                'umur' => 7,
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => Carbon::create(2017, 12, 4),
                'created_at' => Carbon::create(2024, 12, 28),
                'no_hp' => '85832471186',
                'nik' => null,
                'alamat' => ''
            ],
            [
                'id' => 20,
                'nama_lengkap' => 'Aura Noviyanti Sudiro',
                'jenis_kelamin' => 'P',
                'umur' => 27,
                'tempat_lahir' => 'Bekasi',
                'tanggal_lahir' => Carbon::create(1997, 11, 5),
                'created_at' => Carbon::create(2024, 12, 29),
                'no_hp' => '81520365376',
                'nik' => null,
                'alamat' => ''
            ],
            [
                'id' => 21,
                'nama_lengkap' => 'Muhammad Nasir',
                'jenis_kelamin' => 'L',
                'umur' => 43,
                'tempat_lahir' => 'Bengkulu',
                'tanggal_lahir' => Carbon::create(1979, 4, 18),
                'created_at' => Carbon::create(2024, 12, 29),
                'no_hp' => '8111344579',
                'nik' => null,
                'alamat' => ''
            ],
        ];

        Patient::insert($patients);

        $patients2 = [
    [
        'nama_lengkap' => 'Setiawan',
        'jenis_kelamin' => 'L',
        'umur' => 51,
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1974-05-28',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '086755532938',
        'nik' => '4467694591623557',
        'alamat' => 'Griya Cileungsi Blok D3 No 29'
    ],
    [
        'nama_lengkap' => 'Sutiono',
        'jenis_kelamin' => 'L',
        'umur' => 27,
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1997-08-26',
        'created_at' => Carbon::create(2024, 11, 4),
        'no_hp' => '084170952745',
        'nik' => '8235864152171378',
        'alamat' => 'Grand Cibubur Blok B3 No 11'
    ],
    [
        'nama_lengkap' => 'Nurhayati',
        'jenis_kelamin' => 'P',
        'umur' => 51,
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1973-11-02',
        'created_at' => Carbon::create(2024, 11, 5),
        'no_hp' => '086021591176',
        'nik' => '6025772626907151',
        'alamat' => 'Komplek Bojong Blok D3 No 17'
    ],
    [
        'nama_lengkap' => 'Oki Aditia Saputra',
        'jenis_kelamin' => 'L',
        'umur' => 54,
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1971-05-01',
        'created_at' => Carbon::create(2024, 11, 6),
        'no_hp' => '087323541927',
        'nik' => '2495188362409682',
        'alamat' => 'Margahayu Blok A4 No 10'
    ],
    [
        'nama_lengkap' => 'Hendrio Junior',
        'jenis_kelamin' => 'L',
        'umur' => 48,
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1976-09-08',
        'created_at' => Carbon::create(2024, 11, 7),
        'no_hp' => '087423547276',
        'nik' => '9993164241886321',
        'alamat' => 'Komplek Bojong Blok C3 No 7'
    ],
    [
        'nama_lengkap' => 'Giatno',
        'jenis_kelamin' => 'L',
        'umur' => 29,
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1996-02-07',
        'created_at' => Carbon::create(2024, 11, 8),
        'no_hp' => '080870133499',
        'nik' => '0124617569243649',
        'alamat' => 'Komplek Bojong Blok B1 No 28'
    ],
    [
        'nama_lengkap' => 'Siti Ngaisah',
        'jenis_kelamin' => 'P',
        'umur' => 47,
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '1978-04-06',
        'created_at' => Carbon::create(2024, 11, 9),
        'no_hp' => '086148865877',
        'nik' => '6484957434296624',
        'alamat' => 'Margahayu Blok C4 No 8'
    ],
    [
        'nama_lengkap' => 'Ahmad Rasyid',
        'jenis_kelamin' => 'L',
        'umur' => 30,
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1995-07-02',
        'created_at' => Carbon::create(2024, 11, 10),
        'no_hp' => '087185476123',
        'nik' => '8869076643369935',
        'alamat' => 'Margahayu Blok A2 No 10'
    ],
    [
        'nama_lengkap' => 'Gilang Nur Bekti',
        'jenis_kelamin' => 'L',
        'umur' => 33,
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1991-09-17',
        'created_at' => Carbon::create(2024, 11, 11),
        'no_hp' => '088221154935',
        'nik' => '4696332813260518',
        'alamat' => 'Grand Cibubur Blok C5 No 23'
    ],
    [
        'nama_lengkap' => 'Abas Suyatno',
        'jenis_kelamin' => 'L',
        'umur' => 41,
        'tempat_lahir' => 'Semarang',
        'tanggal_lahir' => '1984-07-20',
        'created_at' => Carbon::create(2024, 11, 12),
        'no_hp' => '084852567816',
        'nik' => '1764818433593071',
        'alamat' => 'Komplek Bojong Blok D5 No 7'
    ],
    [
        'nama_lengkap' => 'Kholipah',
        'jenis_kelamin' => 'P',
        'umur' => 51,
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1974-05-31',
        'created_at' => Carbon::create(2024, 11, 13),
        'no_hp' => '080299995285',
        'nik' => '6911587619201329',
        'alamat' => 'Margahayu Blok B4 No 13'
    ],
    [
        'nama_lengkap' => 'Abdul Kholik',
        'jenis_kelamin' => 'L',
        'umur' => 44,
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1980-11-14',
        'created_at' => Carbon::create(2024, 11, 14),
        'no_hp' => '089767295873',
        'nik' => '8145009280433868',
        'alamat' => 'Komplek Bojong Blok B4 No 26'
    ],
    [
        'nama_lengkap' => 'Dede Adiyanto',
        'jenis_kelamin' => 'L',
        'umur' => 50,
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1974-09-24',
        'created_at' => Carbon::create(2024, 11, 15),
        'no_hp' => '086080452101',
        'nik' => '4389506126937719',
        'alamat' => 'Komplek Bojong Blok C9 No 16'
    ],
    [
        'nama_lengkap' => 'Handani Nurul Hidayah',
        'jenis_kelamin' => 'P',
        'umur' => 51,
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1974-08-06',
        'created_at' => Carbon::create(2024, 11, 16),
        'no_hp' => '083303310634',
        'nik' => '7814111024571939',
        'alamat' => 'Grand Cibubur Blok C4 No 13'
    ],
    [
        'nama_lengkap' => 'Mustofa',
        'jenis_kelamin' => 'L',
        'umur' => 50,
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1974-08-20',
        'created_at' => Carbon::create(2024, 11, 17),
        'no_hp' => '082875311219',
        'nik' => '3402200379659621',
        'alamat' => 'Griya Cileungsi Blok C9 No 23'
    ],
    [
        'nama_lengkap' => 'Luhur Gunawan',
        'jenis_kelamin' => 'L',
        'umur' => 31,
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1994-03-30',
        'created_at' => Carbon::create(2024, 11, 18),
        'no_hp' => '082190906448',
        'nik' => '8034086978062372',
        'alamat' => 'Grand Cibubur Blok A5 No 22'
    ],
    [
        'nama_lengkap' => 'Tri Mandrasih',
        'jenis_kelamin' => 'P',
        'umur' => 45,
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1979-12-24',
        'created_at' => Carbon::create(2024, 11, 19),
        'no_hp' => '086395553365',
        'nik' => '2705377200629948',
        'alamat' => 'Komplek Bojong Blok B7 No 9'
    ],
    [
        'nama_lengkap' => 'Manisem',
        'jenis_kelamin' => 'P',
        'umur' => 51,
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1974-03-06',
        'created_at' => Carbon::create(2024, 11, 20),
        'no_hp' => '089836501603',
        'nik' => '9519610947127477',
        'alamat' => 'Griya Cileungsi Blok D3 No 15'
    ],
    [
        'nama_lengkap' => 'Rahmat Widodo',
        'jenis_kelamin' => 'L',
        'umur' => 36,
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1988-10-03',
        'created_at' => Carbon::create(2024, 11, 21),
        'no_hp' => '086217512252',
        'nik' => '5374677383460350',
        'alamat' => 'Grand Cibubur Blok D3 No 27'
    ],
    [
        'nama_lengkap' => 'Ismanto',
        'jenis_kelamin' => 'L',
        'umur' => 32,
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1992-09-14',
        'created_at' => Carbon::create(2024, 11, 22),
        'no_hp' => '088478420158',
        'nik' => '3890524922125371',
        'alamat' => 'Margahayu Blok C6 No 26'
    ],
    [
        'nama_lengkap' => 'Tri Lestari',
        'jenis_kelamin' => 'P',
        'umur' => 49,
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1976-05-14',
        'created_at' => Carbon::create(2024, 11, 23),
        'no_hp' => '087280502834',
        'nik' => '1374465345057903',
        'alamat' => 'Margahayu Blok B6 No 26'
    ],
    [
        'nama_lengkap' => 'Kurniawan Zam Zami',
        'jenis_kelamin' => 'L',
        'umur' => 39,
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1986-03-01',
        'created_at' => Carbon::create(2024, 11, 24),
        'no_hp' => '082968542368',
        'nik' => '5743745563848384',
        'alamat' => 'Komplek Bojong Blok D7 No 27'
    ],
    [
        'nama_lengkap' => 'Raditia Saputri',
        'jenis_kelamin' => 'L',
        'umur' => 32,
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '1993-05-11',
        'created_at' => Carbon::create(2024, 11, 25),
        'no_hp' => '084529507503',
        'nik' => '2497435438297207',
        'alamat' => 'Grand Cibubur Blok B6 No 6'
    ],
    [
        'nama_lengkap' => 'Mabruro',
        'jenis_kelamin' => 'L',
        'umur' => 30,
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1995-01-19',
        'created_at' => Carbon::create(2024, 11, 26),
        'no_hp' => '080964469002',
        'nik' => '1866002583066270',
        'alamat' => 'Grand Cibubur Blok C2 No 29'
    ],
];

Patient::insert($patients2);

$patients3 = [
    [
        'nama_lengkap' => 'Sumarno',
        'jenis_kelamin' => 'L',
        'umur' => '24',
        'tempat_lahir' => 'Semarang',
        'tanggal_lahir' => '2001-09-23',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '084676407831',
        'nik' => null,
        'alamat' => 'Margahayu No. 18',
    ],
    [
        'nama_lengkap' => 'Siti Khasana',
        'jenis_kelamin' => 'P',
        'umur' => '36',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1989-03-18',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '089939139178',
        'nik' => null,
        'alamat' => 'Margahayu No. 8',
    ],
    [
        'nama_lengkap' => 'Muhammad Alfaqih',
        'jenis_kelamin' => 'L',
        'umur' => '46',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '1979-11-23',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '082099635072',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 99',
    ],
    [
        'nama_lengkap' => 'Wagiyo',
        'jenis_kelamin' => 'L',
        'umur' => '52',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1973-01-11',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '083500098949',
        'nik' => null,
        'alamat' => 'Margahayu No. 84',
    ],
    [
        'nama_lengkap' => 'Widi Yanti',
        'jenis_kelamin' => 'P',
        'umur' => '41',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '1984-12-11',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '089408057546',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 21',
    ],
    [
        'nama_lengkap' => 'Fitria Lestari',
        'jenis_kelamin' => 'P',
        'umur' => '23',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '2002-12-25',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '086094877351',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 62',
    ],
    [
        'nama_lengkap' => 'Muji Astuti',
        'jenis_kelamin' => 'P',
        'umur' => '44',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '1981-05-05',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '082588003397',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 4',
    ],
    [
        'nama_lengkap' => 'Nurdiana Saputri',
        'jenis_kelamin' => 'P',
        'umur' => '48',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '1977-11-14',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '087581449284',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 59',
    ],
    [
        'nama_lengkap' => 'Saim',
        'jenis_kelamin' => 'L',
        'umur' => '20',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '2005-12-24',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '089246949227',
        'nik' => null,
        'alamat' => 'Margahayu No. 118',
    ],
    [
        'nama_lengkap' => 'Supingatun',
        'jenis_kelamin' => 'P',
        'umur' => '33',
        'tempat_lahir' => 'Semarang',
        'tanggal_lahir' => '1992-05-06',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '082075588829',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 51',
    ],
    [
        'nama_lengkap' => 'Indra Yani',
        'jenis_kelamin' => 'P',
        'umur' => '23',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '2002-12-15',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '083315313752',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 39',
    ],
    [
        'nama_lengkap' => 'Munawaroh',
        'jenis_kelamin' => 'P',
        'umur' => '20',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '2005-02-22',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '083070481277',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 85',
    ],
    [
        'nama_lengkap' => 'Sanadi Saleh',
        'jenis_kelamin' => 'L',
        'umur' => '49',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1976-06-02',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '081826065563',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 119',
    ],
    [
        'nama_lengkap' => 'Musaadah',
        'jenis_kelamin' => 'P',
        'umur' => '28',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '1997-11-06',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '083205063106',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 96',
    ],
    [
        'nama_lengkap' => 'Jurianto',
        'jenis_kelamin' => 'L',
        'umur' => '34',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1991-12-18',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '085909048311',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 35',
    ],
    [
        'nama_lengkap' => 'Sri Wahyuni',
        'jenis_kelamin' => 'P',
        'umur' => '53',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1972-12-12',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '088306316002',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 113',
    ],
    [
        'nama_lengkap' => 'Pratama Ade Kurniawan',
        'jenis_kelamin' => 'L',
        'umur' => '53',
        'tempat_lahir' => 'Semarang',
        'tanggal_lahir' => '1972-05-01',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '089497620476',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 105',
    ],
    [
        'nama_lengkap' => 'Erianto',
        'jenis_kelamin' => 'L',
        'umur' => '29',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1996-12-13',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '081055669398',
        'nik' => null,
        'alamat' => 'Margahayu No. 57',
    ],
    [
        'nama_lengkap' => 'Tuti Rahayu',
        'jenis_kelamin' => 'P',
        'umur' => '29',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1996-05-27',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '083676024605',
        'nik' => null,
        'alamat' => 'Margahayu No. 17',
    ],
    [
        'nama_lengkap' => 'Apri Ayu Angelica',
        'jenis_kelamin' => 'P',
        'umur' => '50',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1975-03-04',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '082885215624',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 99',
    ],
    [
        'nama_lengkap' => 'Muhammad Rizky Aprianto',
        'jenis_kelamin' => 'L',
        'umur' => '54',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '1971-03-05',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '088062898700',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 35',
    ],
    [
        'nama_lengkap' => 'Ahmad Zainuri',
        'jenis_kelamin' => 'L',
        'umur' => '51',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1974-01-16',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '086880833797',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 21',
    ],
    [
        'nama_lengkap' => 'Ari Sarianto',
        'jenis_kelamin' => 'L',
        'umur' => '38',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1987-04-02',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '084118831014',
        'nik' => null,
        'alamat' => 'Margahayu No. 20',
    ],
    [
        'nama_lengkap' => 'Hasyim Asy\'Ari',
        'jenis_kelamin' => 'L',
        'umur' => '42',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1983-09-22',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '082162360948',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 107',
    ],
    [
        'nama_lengkap' => 'Suritno',
        'jenis_kelamin' => 'L',
        'umur' => '41',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1984-05-05',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '083348009245',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 81',
    ],
    [
        'nama_lengkap' => 'Susanti',
        'jenis_kelamin' => 'P',
        'umur' => '36',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '1989-06-11',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '082591535278',
        'nik' => null,
        'alamat' => 'Margahayu No. 85',
    ],
    [
        'nama_lengkap' => 'Mochamad Sarengat',
        'jenis_kelamin' => 'L',
        'umur' => '31',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1994-02-23',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '089921436583',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 46',
    ],
    [
        'nama_lengkap' => 'Sumari',
        'jenis_kelamin' => 'L',
        'umur' => '26',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1999-07-12',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '087630024614',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 65',
    ],
    [
        'nama_lengkap' => 'Suminten',
        'jenis_kelamin' => 'P',
        'umur' => '21',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '2004-03-05',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '085648105236',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 114',
    ],
    [
        'nama_lengkap' => 'Susi Susanti',
        'jenis_kelamin' => 'P',
        'umur' => '49',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1976-09-08',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '082267485517',
        'nik' => null,
        'alamat' => 'Margahayu No. 43',
    ],
    [
        'nama_lengkap' => 'Bagus Suryanto',
        'jenis_kelamin' => 'L',
        'umur' => '24',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '2001-08-16',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '081029678095',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 44',
    ],
    [
        'nama_lengkap' => 'Umi Naviah',
        'jenis_kelamin' => 'P',
        'umur' => '28',
        'tempat_lahir' => 'Semarang',
        'tanggal_lahir' => '1997-11-02',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '081688455663',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 70',
    ],
    [
        'nama_lengkap' => 'Aqra Nabiha Anindita',
        'jenis_kelamin' => 'P',
        'umur' => '22',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '2003-08-12',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '083099134514',
        'nik' => null,
        'alamat' => 'Margahayu No. 99',
    ],
    [
        'nama_lengkap' => 'Mursino',
        'jenis_kelamin' => 'L',
        'umur' => '28',
        'tempat_lahir' => 'Semarang',
        'tanggal_lahir' => '1997-12-23',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '085302572645',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 56',
    ],
    [
        'nama_lengkap' => 'Kasyani',
        'jenis_kelamin' => 'P',
        'umur' => '47',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1978-10-17',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '088482068492',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 104',
    ],
    [
        'nama_lengkap' => 'Muhamad Arif Harfiyanto',
        'jenis_kelamin' => 'L',
        'umur' => '45',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '1980-07-07',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '085759100532',
        'nik' => null,
        'alamat' => 'Margahayu No. 108',
    ],
    [
        'nama_lengkap' => 'Novia Nurhayati',
        'jenis_kelamin' => 'P',
        'umur' => '35',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1990-04-16',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '084006870381',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 90',
    ],
    [
        'nama_lengkap' => 'Mansyur',
        'jenis_kelamin' => 'L',
        'umur' => '22',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '2003-08-27',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '082115266517',
        'nik' => null,
        'alamat' => 'Margahayu No. 50',
    ],
    [
        'nama_lengkap' => 'Giarsih',
        'jenis_kelamin' => 'P',
        'umur' => '54',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1971-10-13',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '082602264274',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 50',
    ],

    [
        'nama_lengkap' => 'Vika Kumala Putri',
        'jenis_kelamin' => 'P',
        'umur' => '52',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1973-03-23',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '081579394329',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 18',
    ],
    [
        'nama_lengkap' => 'Muhamat Saiful Safi\'I',
        'jenis_kelamin' => 'L',
        'umur' => '52',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1973-01-15',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '086010461227',
        'nik' => null,
        'alamat' => 'Margahayu No. 91',
    ],
    [
        'nama_lengkap' => 'Warsini',
        'jenis_kelamin' => 'P',
        'umur' => '43',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1982-08-12',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '085729388490',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 24',
    ],
    [
        'nama_lengkap' => 'Dimaz Reza Ramadhan',
        'jenis_kelamin' => 'L',
        'umur' => '35',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1990-06-26',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '088644310212',
        'nik' => null,
        'alamat' => 'Margahayu No. 120',
    ],
    [
        'nama_lengkap' => 'Miseri',
        'jenis_kelamin' => 'L',
        'umur' => '35',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1990-10-10',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '081479829782',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 120',
    ],
    [
        'nama_lengkap' => 'Wartinah',
        'jenis_kelamin' => 'P',
        'umur' => '48',
        'tempat_lahir' => 'Semarang',
        'tanggal_lahir' => '1977-03-03',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '085922752878',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 58',
    ],
    [
        'nama_lengkap' => 'Agus Nuryanto',
        'jenis_kelamin' => 'L',
        'umur' => '43',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1982-06-08',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '085471814376',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 33',
    ],
    [
        'nama_lengkap' => 'Syahrul Widianto',
        'jenis_kelamin' => 'L',
        'umur' => '25',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '2000-06-25',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '081513193910',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 98',
    ],
    [
        'nama_lengkap' => 'Alif Ardana',
        'jenis_kelamin' => 'L',
        'umur' => '39',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1986-02-04',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '082957966174',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 90',
    ],
    [
        'nama_lengkap' => 'Mujianto',
        'jenis_kelamin' => 'L',
        'umur' => '44',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1981-04-20',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '089082785637',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 51',
    ],
    [
        'nama_lengkap' => 'Puji Astuti',
        'jenis_kelamin' => 'P',
        'umur' => '53',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1972-03-05',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '086780363355',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 32',
    ],
    [
        'nama_lengkap' => 'Ahmad Aji Supriono',
        'jenis_kelamin' => 'L',
        'umur' => '33',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1992-05-19',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '087669714295',
        'nik' => null,
        'alamat' => 'Margahayu No. 6',
    ],
    [
        'nama_lengkap' => 'Rifa\'I Dwi Cahyo',
        'jenis_kelamin' => 'L',
        'umur' => '47',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1978-09-19',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '089162218975',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 101',
    ],
    [
        'nama_lengkap' => 'Ayla Amelia Nur',
        'jenis_kelamin' => 'P',
        'umur' => '21',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '2004-04-01',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '083110568112',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 25',
    ],
    [
        'nama_lengkap' => 'Karmidi',
        'jenis_kelamin' => 'L',
        'umur' => '29',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1996-10-09',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '089740197464',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 29',
    ],
    [
        'nama_lengkap' => 'Wilmaini',
        'jenis_kelamin' => 'P',
        'umur' => '24',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '2001-02-14',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '089545993981',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 29',
    ],
    [
        'nama_lengkap' => 'Debyo Widya Anggara',
        'jenis_kelamin' => 'L',
        'umur' => '43',
        'tempat_lahir' => 'Semarang',
        'tanggal_lahir' => '1982-12-27',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '082659149784',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 118',
    ],
    [
        'nama_lengkap' => 'Silvi Widya Pangesti',
        'jenis_kelamin' => 'P',
        'umur' => '40',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1985-10-05',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '088421232178',
        'nik' => null,
        'alamat' => 'Margahayu No. 116',
    ],
    [
        'nama_lengkap' => 'Auliya Nur Syahidah',
        'jenis_kelamin' => 'P',
        'umur' => '41',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1984-09-08',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '087729952844',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 117',
    ],
    [
        'nama_lengkap' => 'Azzah Rotun Nisa Almufidah',
        'jenis_kelamin' => 'P',
        'umur' => '45',
        'tempat_lahir' => 'Semarang',
        'tanggal_lahir' => '1980-08-17',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '089540724644',
        'nik' => null,
        'alamat' => 'Margahayu No. 64',
    ],
    [
        'nama_lengkap' => 'Sariman',
        'jenis_kelamin' => 'L',
        'umur' => '25',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '2000-08-20',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '086728435926',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 22',
    ],
    [
        'nama_lengkap' => 'Parni',
        'jenis_kelamin' => 'P',
        'umur' => '24',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '2001-05-02',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '088819977280',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 18',
    ],
    [
        'nama_lengkap' => 'Haspar Sutedi',
        'jenis_kelamin' => 'L',
        'umur' => '31',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1994-09-22',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '081873103367',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 51',
    ],
    [
        'nama_lengkap' => 'Sudarmi',
        'jenis_kelamin' => 'P',
        'umur' => '54',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1971-11-07',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '089783114558',
        'nik' => null,
        'alamat' => 'Margahayu No. 73',
    ],
    [
        'nama_lengkap' => 'Suparno',
        'jenis_kelamin' => 'L',
        'umur' => '31',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1994-09-18',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '081559343641',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 51',
    ],
    [
        'nama_lengkap' => 'Dewi Fitria',
        'jenis_kelamin' => 'P',
        'umur' => '40',
        'tempat_lahir' => 'Semarang',
        'tanggal_lahir' => '1985-11-07',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '086700220487',
        'nik' => null,
        'alamat' => 'Margahayu No. 27',
    ],
    [
        'nama_lengkap' => 'Hadista Nadratul Zanah',
        'jenis_kelamin' => 'P',
        'umur' => '52',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1973-03-11',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '087099860998',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 48',
    ],
    [
        'nama_lengkap' => 'Rafkan Djovanka Al Fariz',
        'jenis_kelamin' => 'L',
        'umur' => '54',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1971-11-23',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '086210979841',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 71',
    ],
    [
        'nama_lengkap' => 'Volint',
        'jenis_kelamin' => 'L',
        'umur' => '33',
        'tempat_lahir' => 'Semarang',
        'tanggal_lahir' => '1992-05-16',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '088030144508',
        'nik' => null,
        'alamat' => 'Margahayu No. 89',
    ],
    [
        'nama_lengkap' => 'Sri Natalia',
        'jenis_kelamin' => 'P',
        'umur' => '24',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '2001-08-01',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '089089248370',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 75',
    ],
    [
        'nama_lengkap' => 'Virly Karista Balqis',
        'jenis_kelamin' => 'P',
        'umur' => '48',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1977-10-20',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '083467032336',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 83',
    ],
    [
        'nama_lengkap' => 'Wasyaraffa Al Hafiz',
        'jenis_kelamin' => 'L',
        'umur' => '43',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '1982-04-14',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '083338970917',
        'nik' => null,
        'alamat' => 'Margahayu No. 101',
    ],
    [
        'nama_lengkap' => 'Nur Sodik',
        'jenis_kelamin' => 'L',
        'umur' => '45',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '1980-02-13',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '085619838535',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 92',
    ],
    [
        'nama_lengkap' => 'Siti Indah Syah',
        'jenis_kelamin' => 'P',
        'umur' => '38',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1987-06-19',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '081004221926',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 39',
    ],
    [
        'nama_lengkap' => 'Nadhirotul Khusniah',
        'jenis_kelamin' => 'P',
        'umur' => '41',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1984-01-04',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '089916846691',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 106',
    ],
    [
        'nama_lengkap' => 'Dewi Masitoh',
        'jenis_kelamin' => 'P',
        'umur' => '22',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '2003-10-18',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '088690783151',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 74',
    ],
    [
        'nama_lengkap' => 'Achmad Moehaimin Alwi',
        'jenis_kelamin' => 'L',
        'umur' => '29',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1996-08-03',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '088393551555',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 99',
    ],
    [
        'nama_lengkap' => 'Siti Aisyah',
        'jenis_kelamin' => 'P',
        'umur' => '43',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1982-11-26',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '085826386564',
        'nik' => null,
        'alamat' => 'Margahayu No. 83',
    ],
    [
        'nama_lengkap' => 'Muhammad Faizin Alwi',
        'jenis_kelamin' => 'L',
        'umur' => '47',
        'tempat_lahir' => 'Semarang',
        'tanggal_lahir' => '1978-11-03',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '088087365652',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 109',
    ],
    [
        'nama_lengkap' => 'Sarno',
        'jenis_kelamin' => 'L',
        'umur' => '21',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '2004-08-08',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '088255483829',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 41',
    ],
    [
        'nama_lengkap' => 'Giyem',
        'jenis_kelamin' => 'P',
        'umur' => '44',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1981-01-26',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '086247222248',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 96',
    ],
    [
        'nama_lengkap' => 'Siti Khasanah',
        'jenis_kelamin' => 'P',
        'umur' => '33',
        'tempat_lahir' => 'Semarang',
        'tanggal_lahir' => '1992-04-06',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '082408283669',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 45',
    ],
    [
        'nama_lengkap' => 'Andrianto',
        'jenis_kelamin' => 'L',
        'umur' => '36',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1989-05-19',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '083643342407',
        'nik' => null,
        'alamat' => 'Margahayu No. 94',
    ],
    [
        'nama_lengkap' => 'Tri Purwanti',
        'jenis_kelamin' => 'P',
        'umur' => '29',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1996-11-14',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '083635469027',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 30',
    ],
    [
        'nama_lengkap' => 'Fajri Syahdan Naufal',
        'jenis_kelamin' => 'L',
        'umur' => '29',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '1996-04-28',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '088410944896',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 48',
    ],
    [
        'nama_lengkap' => 'Wahidi',
        'jenis_kelamin' => 'L',
        'umur' => '55',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1970-08-12',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '084598329720',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 33',
    ],
    [
        'nama_lengkap' => 'Jasiah',
        'jenis_kelamin' => 'P',
        'umur' => '24',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '2001-08-15',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '087864295741',
        'nik' => null,
        'alamat' => 'Margahayu No. 93',
    ],
    [
        'nama_lengkap' => 'Eliyuswisnawaty',
        'jenis_kelamin' => 'P',
        'umur' => '35',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1990-07-12',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '088104757090',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 106',
    ],
    [
        'nama_lengkap' => 'Sukijan',
        'jenis_kelamin' => 'L',
        'umur' => '20',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '2005-07-09',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '081767149651',
        'nik' => null,
        'alamat' => 'Margahayu No. 65',
    ],
    [
        'nama_lengkap' => 'Siti Zaenap',
        'jenis_kelamin' => 'P',
        'umur' => '29',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1996-03-13',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '088600456660',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 111',
    ],
    [
        'nama_lengkap' => 'Sodikin',
        'jenis_kelamin' => 'L',
        'umur' => '37',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '1988-12-08',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '084373769314',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 119',
    ],
    [
        'nama_lengkap' => 'Mas\' Ud',
        'jenis_kelamin' => 'L',
        'umur' => '22',
        'tempat_lahir' => 'Semarang',
        'tanggal_lahir' => '2003-06-05',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '083504875394',
        'nik' => null,
        'alamat' => 'Margahayu No. 33',
    ],
    [
        'nama_lengkap' => 'Sutinem',
        'jenis_kelamin' => 'P',
        'umur' => '28',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1997-09-23',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '089650892658',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 44',
    ],
    [
        'nama_lengkap' => 'Ahmad Safi\'I',
        'jenis_kelamin' => 'L',
        'umur' => '48',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1977-06-19',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '082126538472',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 19',
    ],
    [
        'nama_lengkap' => 'Habibi Nurrohim',
        'jenis_kelamin' => 'L',
        'umur' => '24',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '2001-09-05',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '087854955638',
        'nik' => null,
        'alamat' => 'Grand Cibubur No. 86',
    ],
    [
        'nama_lengkap' => 'Sulasikin Nasukah',
        'jenis_kelamin' => 'P',
        'umur' => '50',
        'tempat_lahir' => 'Semarang',
        'tanggal_lahir' => '1975-12-27',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '082185038965',
        'nik' => null,
        'alamat' => 'Margahayu No. 14',
    ],
    [
        'nama_lengkap' => 'Jamilatun Azizah',
        'jenis_kelamin' => 'P',
        'umur' => '22',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '2003-03-02',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '083473236488',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 60',
    ],
    [
        'nama_lengkap' => 'Suparlan',
        'jenis_kelamin' => 'L',
        'umur' => '45',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '1980-08-08',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '084191082570',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 71',
    ],
    [
        'nama_lengkap' => 'Sulastri',
        'jenis_kelamin' => 'P',
        'umur' => '22',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '2003-01-13',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '084867850072',
        'nik' => null,
        'alamat' => 'Margahayu No. 57',
    ],
    [
        'nama_lengkap' => 'Widyo Wati',
        'jenis_kelamin' => 'P',
        'umur' => '39',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1986-03-17',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '082517070149',
        'nik' => null,
        'alamat' => 'Margahayu No. 36',
    ],
    [
        'nama_lengkap' => 'Wiwit Widia Wati',
        'jenis_kelamin' => 'P',
        'umur' => '28',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1997-10-24',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '084708458744',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 30',
    ],
    [
        'nama_lengkap' => 'Wulandari',
        'jenis_kelamin' => 'P',
        'umur' => '37',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1988-01-26',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '082553420190',
        'nik' => null,
        'alamat' => 'Margahayu No. 84',
    ],
    [
        'nama_lengkap' => 'Kirno Yudi',
        'jenis_kelamin' => 'L',
        'umur' => '23',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '2002-02-16',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '082226997878',
        'nik' => null,
        'alamat' => 'Margahayu No. 85',
    ],
    [
        'nama_lengkap' => 'Lilik Mujiati',
        'jenis_kelamin' => 'P',
        'umur' => '39',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1986-04-16',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '081978837566',
        'nik' => null,
        'alamat' => 'Margahayu No. 44',
    ],
    [
        'nama_lengkap' => 'Shofiyyatun Dzakiroh',
        'jenis_kelamin' => 'P',
        'umur' => '48',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '1977-02-22',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '084212436188',
        'nik' => null,
        'alamat' => 'Margahayu No. 45',
    ],
    [
        'nama_lengkap' => 'Wulan Maratussholikha',
        'jenis_kelamin' => 'P',
        'umur' => '20',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '2005-07-26',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '088245777756',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 27',
    ],
    [
        'nama_lengkap' => 'Aris Tiono',
        'jenis_kelamin' => 'L',
        'umur' => '43',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '1982-09-03',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '086269717535',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 94',
    ],
    [
        'nama_lengkap' => 'Sitti Julaeha',
        'jenis_kelamin' => 'P',
        'umur' => '39',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1986-08-22',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '081472777687',
        'nik' => null,
        'alamat' => 'Margahayu No. 1',
    ],
    [
        'nama_lengkap' => 'Mirza Hamizan Alfaeyza',
        'jenis_kelamin' => 'L',
        'umur' => '29',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1996-03-15',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '085893704857',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 67',
    ],
    [
        'nama_lengkap' => 'Apri Hantoro',
        'jenis_kelamin' => 'L',
        'umur' => '41',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1984-02-02',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '085881748193',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 22',
    ],
    [
        'nama_lengkap' => 'Suratman',
        'jenis_kelamin' => 'L',
        'umur' => '32',
        'tempat_lahir' => 'Bogor',
        'tanggal_lahir' => '1993-01-06',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '087612220918',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 46',
    ],
    [
        'nama_lengkap' => 'Mucharomatun',
        'jenis_kelamin' => 'P',
        'umur' => '25',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '2000-11-07',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '085319041663',
        'nik' => null,
        'alamat' => 'Margahayu No. 116',
    ],
    [
        'nama_lengkap' => 'Rensy Herwinda',
        'jenis_kelamin' => 'P',
        'umur' => '47',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '1978-11-20',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '089548931585',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 99',
    ],
    [
        'nama_lengkap' => 'Sukarmin',
        'jenis_kelamin' => 'L',
        'umur' => '38',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1987-11-25',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '083974691328',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 60',
    ],
    [
        'nama_lengkap' => 'Saniri',
        'jenis_kelamin' => 'P',
        'umur' => '43',
        'tempat_lahir' => 'Semarang',
        'tanggal_lahir' => '1982-11-05',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '087350471369',
        'nik' => null,
        'alamat' => 'Margahayu No. 74',
    ],
    [
        'nama_lengkap' => 'Firda Ramadan',
        'jenis_kelamin' => 'L',
        'umur' => '24',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '2001-11-24',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '082194127781',
        'nik' => null,
        'alamat' => 'Griya Cileungsi No. 75',
    ],
    [
        'nama_lengkap' => 'Fauzi Hidayat',
        'jenis_kelamin' => 'L',
        'umur' => '23',
        'tempat_lahir' => 'Tangerang',
        'tanggal_lahir' => '2002-09-03',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '089762090413',
        'nik' => null,
        'alamat' => 'Margahayu No. 100',
    ],
    [
        'nama_lengkap' => 'Ahmad Suyadi',
        'jenis_kelamin' => 'L',
        'umur' => '20',
        'tempat_lahir' => 'Bekasi',
        'tanggal_lahir' => '2005-09-27',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '083223070710',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 34',
    ],
    [
        'nama_lengkap' => 'Nuriah',
        'jenis_kelamin' => 'P',
        'umur' => '48',
        'tempat_lahir' => 'Bandung',
        'tanggal_lahir' => '1977-09-08',
        'created_at' => Carbon::create(2024, 11, 3),
        'no_hp' => '088552531349',
        'nik' => null,
        'alamat' => 'Komplek Bojong No. 49',
    ],
];

Patient::insert($patients3);
    }
}
